spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ektour-database.cfuvayewpcok.ap-northeast-2.rds.amazonaws.com:3306/ek-tour
    username: admin
    password: asdf1234
